### PR TITLE
Added offset parameter. smoothScroll now takes list of arguments or arguments object.

### PR DESCRIPTION
**Pull request by cideM**
This is my first PR ever so please have mercy. The offset option is a simple number that is added to `end`. Additionally, as the list of optional parameters is quite long now, I made it possible to add options via a plain object. That way you don't have to `smoothScroll(target, null, null ...)`. 
Please let me know if I overlooked something. If my PR is complete crap, be honest about it, I can take it (and cry a little).

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey @alicelieutier any chance of your merging this? I really need it, as otherwise the floating navigation bar on my side is always on top of the area the user focused to.

**Review by ganeshmunisifreddy — APPROVED** [review]
seems good to approve.

**Comment by cideM** [comment]
Wow this has been a while, hello younger me. I'll look into the merge conflict tonight. I don't even have the original fork anymore so maybe it's easier if I just create a new fork/PR. Also take a look at what I did back then.

**Comment by camslice** [comment]
bump

**Comment by cideM** [comment]
This is now superseded by #48 which is a renewal of this PR without the bugs and conflicts

**Pull request closed without merging**
