### PR TITLE
Support isomorphic

### PR DESCRIPTION
**Pull request by t1mmen**
This PR adds support for isomorphic/serverside rendering, ~~by defining the window & document objects if they're unset.~~ (this turned out now to work so well)

Basically all this does it:
```
if (typeof window === 'object' && typeof document === 'object') {
    // window.smoothScroll......
}
```

### CODE REVIEW

**Comment by alicelieutier** [comment]
Why is the diff basically changing every line? I know github diff view isn't ideal, but is it just picking on indentation? I'd rather maintain the blame..
Maybe we can just define the function into a variable, and then attach it to window if it's an object?

**Comment by t1mmen** [comment]
The diff is basically all indentation, yes. It's just wrapped in an "if window / document exists" check.

Your solution should work fine too.

— Timm

**Comment by t1mmen** [comment]
@alicelieutier, I've updated the PR with changes as you requested. Hope this is more to your liking.

(NB: I didn't change the `min` version at all, as I wasn't sure which minifier you used)

**Comment by alicelieutier** [comment]
Thanks!
This wasn't to annoy you, I just think keeping the blame is useful.
I think the last minifier I used was http://jscompress.com/ but I have no strong opinion on the matter. I'd like it if you could add the minified file.

**Comment by t1mmen** [comment]
Oh, sorry, I didn't mean to imply you were doing this to be annoying :) You are quite right about keeping blame.

I've added the minified version via  http://jscompress.com/ now.

**Pull request merged**
