### PR TITLE
Adds a package.json file

### PR DESCRIPTION
**Pull request by kennethormandy**
Hey! This is a really useful script, thanks for writing it. I was hoping to install it as a dependency through [npm](https://npmjs.com), this pull request just adds a `package.json` file to make that possible.

If you wanted to publish it to the npm registry, I think you should just need to run:

```
npm publish
```

…after merging the pull request. Then, anyone can install it using:

```
npm install smoothscroll
```

If you’d rather not do that, it will still be possible to install it via GitHub:

```
npm install alicelieutier/smoothScroll
```

I’d be happy to update the README depending on which one you’d prefer. Thanks!

### CODE REVIEW

**Comment by alicelieutier** [comment]
Hey, this is a great idea!
I never published a package to npm, but I am happy to. I'll wait on you change in the README to merge, then.

**Comment by kennethormandy** [comment]
There you go :)

**Comment by alicelieutier** [comment]
Thanks !

**Comment by alicelieutier** [comment]
Ok, just published it: https://www.npmjs.com/package/smoothscroll
Thanks :)

**Pull request merged**
