### PR TITLE
Add umd wrapper

### PR DESCRIPTION
**Pull request by ahoym**
Contributors: @alicelieutier, @t1mmen
Relevant discussion and previous test branch this was built off of: https://github.com/alicelieutier/smoothScroll/pull/12.

Rebased off of https://github.com/alicelieutier/smoothScroll/pull/11, to include @t1mmen's contributions to allowing isomorphic rendering.

This PR contains a single clean commit. It: 
+ Adds a UMD wrapper around smoothScroll 
+ This wrapper supports CommonJS/NodeJS and RequireJS module formats. 
+ When executed as a `<script>`, it will attach to the window as done prior to this pull.
+ Add `'use strict';` statements to functions to prevent unintended behavior with `this` inside functions.
+ Add minified version through [jscompress](http://jscompress.com/) compression 

For information on the basis of this UMD wrapper: http://toddmotto.com/what-function-window-document-undefined-iife-really-means/

### CODE REVIEW

**Comment by alicelieutier** [comment]
giphy

**Comment by ahoym** [comment]
@alicelieutier can you npm publish this new version? I also noticed you don't have any tagged releases, so here's a quick run down to get it up:

1. Change version number in `package.json` to newer version, like 0.2.0
1. Commit change to master
1. Pull down newest master (with the new version change now)
1. `git tag 0.2.0`
1. `git push origin 0.2.0`
1. `npm publish`

**Comment by alicelieutier** [comment]
Thanks! I've done that now.

**Comment by ahoym** [comment]
:tada: :balloon: :tada: :balloon: :tada: :balloon: :tada: :balloon: :tada: :balloon: :tada:

**Pull request merged**
